// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATVWQnYO8TU9p9iDDPW2HmvH2tRMxce2g',
    appId: '1:1078444622339:web:0983081f247d408d5c8436',
    messagingSenderId: '1078444622339',
    projectId: 'bullysafe-db644',
    authDomain: 'bullysafe-db644.firebaseapp.com',
    storageBucket: 'bullysafe-db644.appspot.com',
    measurementId: 'G-Y19ZNQZWTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB78T_3PxRHs9YuqN-Y6zG2d-W_aTdWFLY',
    appId: '1:1078444622339:android:a5620722f02503a85c8436',
    messagingSenderId: '1078444622339',
    projectId: 'bullysafe-db644',
    storageBucket: 'bullysafe-db644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuY8uD0g9Pojv_Nn6HnxXJNCdFhaU5bYQ',
    appId: '1:1078444622339:ios:35244b0ead6648c95c8436',
    messagingSenderId: '1078444622339',
    projectId: 'bullysafe-db644',
    storageBucket: 'bullysafe-db644.appspot.com',
    iosBundleId: 'com.example.flutterApplicationBullysafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuY8uD0g9Pojv_Nn6HnxXJNCdFhaU5bYQ',
    appId: '1:1078444622339:ios:35244b0ead6648c95c8436',
    messagingSenderId: '1078444622339',
    projectId: 'bullysafe-db644',
    storageBucket: 'bullysafe-db644.appspot.com',
    iosBundleId: 'com.example.flutterApplicationBullysafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATVWQnYO8TU9p9iDDPW2HmvH2tRMxce2g',
    appId: '1:1078444622339:web:573e7a0a0f1ec76c5c8436',
    messagingSenderId: '1078444622339',
    projectId: 'bullysafe-db644',
    authDomain: 'bullysafe-db644.firebaseapp.com',
    storageBucket: 'bullysafe-db644.appspot.com',
    measurementId: 'G-FK32NWFM7L',
  );
}
